from __future__ import annotations

STRINGS = {
    "app_title": "Стего Студия — LSB",
    "header": "Стего Студия",
    "compare_title": "Сравнение изображений",
    "original": "Оригинал",
    "modified": "Модифицированное",
    "controls": "Панель управления",
    "open": "Открыть изображение",
    "save_as": "Сохранить как...",
    "export_report": "Экспорт отчёта",
    "export_pack": "Экспорт архива данных",
    "show_hist": "Показать гистограмму LSB",
    "show_compare": "До/После + Теплокарта",
    "attack_lab": "Симулятор атак",
    "benchmark": "Сравнить режимы",
    "demo": "Демо-режим",
    "message": "Сообщение",
    "password": "Пароль (опционально)",
    "bits": "Бит на канал",
    "method": "Метод сокрытия",
    "hide": "Спрятать",
    "extract": "Извлечь",
    "status_wait": "Откройте изображение, чтобы начать работу",
    "risk_unknown": "Риск: —",
}
